import type { Locale } from './i18n';
import { local } from './legal-content';

export type BilingualText = { en: string; ar: string };
export type Guide = { slug: string; category: string; title: BilingualText; summary: BilingualText; sections: { title: BilingualText; body: BilingualText }[]; source: { label: string; url: string } };
export const guidanceCategories = (locale: Locale) => [
  { value: 'business', label: local(locale, 'Business & contracts', 'الأعمال والعقود') },
  { value: 'disputes', label: local(locale, 'Disputes & proceedings', 'النزاعات والإجراءات') },
  { value: 'property', label: local(locale, 'Property', 'العقارات') },
  { value: 'personal', label: local(locale, 'Personal & family', 'الأفراد والأسرة') },
];

// Editorial preparation guides, not attributed publications or individual legal advice.
export const guides: Guide[] = [
  { slug: 'consultation-preparation', category: 'personal', title: { en: 'Preparing for your first legal consultation', ar: 'الاستعداد للاستشارة القانونية الأولى' }, summary: { en: 'A clear timeline, relevant records, and focused questions make your first conversation more useful.', ar: 'يساعد التسلسل الزمني الواضح والمستندات ذات الصلة والأسئلة المحددة في جعل الحوار الأول أكثر فائدة.' }, sections: [
    { title: { en: 'Write a short timeline', ar: 'اكتبوا تسلسلاً زمنياً مختصراً' }, body: { en: 'Note the key events, dates, people involved, and the result you hope to achieve. Separate facts you can document from assumptions or unanswered questions.', ar: 'سجلوا الأحداث والتواريخ والأطراف المعنية والنتيجة المرجوة. افصلوا الوقائع المثبتة بالمستندات عن الافتراضات والأسئلة التي تحتاج إلى إجابة.' } },
    { title: { en: 'Keep relevant records ready', ar: 'جهزوا المستندات ذات الصلة' }, body: { en: 'Keep copies of agreements, correspondence, payment records, and official notices. Do not send sensitive documents with an initial website inquiry; agree a suitable way to share them directly with the office.', ar: 'احتفظوا بنسخ من الاتفاقيات والمراسلات وإثباتات الدفع والإشعارات الرسمية. لا ترسلوا مستندات حساسة مع الاستفسار الأول عبر الموقع؛ اتفقوا مع المكتب مباشرة على طريقة مناسبة لمشاركتها.' } },
    { title: { en: 'Confirm scope and fees', ar: 'أكدوا النطاق والرسوم' }, body: { en: 'Ask what the consultation covers, which documents are needed, and how any fees will be agreed. Sending an inquiry does not confirm an appointment or engage a consultant.', ar: 'اسألوا عما تشمله الاستشارة والمستندات المطلوبة وكيفية الاتفاق على الرسوم. إرسال الاستفسار لا يؤكد موعداً ولا ينشئ علاقة استشارية.' } },
  ], source: { label: 'UAE Government — Justice and safety', url: 'https://u.ae/en/information-and-services/justice-safety-and-the-law' } },
  { slug: 'contract-review', category: 'business', title: { en: 'What to prepare before a contract review', ar: 'ما الذي يلزم قبل مراجعة العقد؟' }, summary: { en: 'Bring the complete agreement and explain the commercial outcome you want to protect.', ar: 'أحضروا الاتفاقية كاملة واشرحوا النتيجة التجارية التي ترغبون في حمايتها.' }, sections: [
    { title: { en: 'Read the complete agreement', ar: 'راجعوا الاتفاقية كاملة' }, body: { en: 'Include schedules, amendments, referenced terms, and earlier drafts. Confirm the identities of the parties, the subject of the agreement, and any language versions.', ar: 'أرفقوا الملاحق والتعديلات والشروط المشار إليها والمسودات السابقة. تحققوا من هوية الأطراف وموضوع الاتفاقية وأي نسخ بلغات أخرى.' } },
    { title: { en: 'Identify practical obligations', ar: 'حددوا الالتزامات العملية' }, body: { en: 'Mark delivery dates, payment terms, renewal provisions, termination clauses, and dispute arrangements. Explain which obligations are unclear or difficult to fulfil.', ar: 'حددوا مواعيد التسليم وشروط الدفع والتجديد والإنهاء وآلية النزاعات. وضحوا الالتزامات غير الواضحة أو التي يصعب تنفيذها.' } },
    { title: { en: 'Raise concerns before signing', ar: 'اطرحوا المخاوف قبل التوقيع' }, body: { en: 'Explain your negotiating priorities and keep a record of proposed changes. The effect of any clause depends on the complete agreement and applicable law; a checklist is not a substitute for a review.', ar: 'وضحوا أولويات التفاوض واحتفظوا بسجل للتعديلات المقترحة. يعتمد أثر أي بند على الاتفاقية كاملة والقانون الواجب التطبيق؛ ولا تغني قائمة المراجعة عن الاستشارة.' } },
  ], source: { label: 'UAE Legislation portal', url: 'https://uaelegislation.gov.ae/en' } },
  { slug: 'employment-records', category: 'business', title: { en: 'Organising records for an employment matter', ar: 'تنظيم المستندات للمسائل العمالية' }, summary: { en: 'Gather the documents that explain your employment relationship and the issue in dispute.', ar: 'اجمعوا المستندات التي توضح علاقة العمل والمسألة محل الخلاف.' }, sections: [
    { title: { en: 'Start with the employment relationship', ar: 'ابدأوا بعلاقة العمل' }, body: { en: 'Prepare your employment contract, amendments, employer details, and dates of joining or leaving. Identify the employer location and whether a specific free-zone framework may apply.', ar: 'جهزوا عقد العمل وتعديلاته وبيانات صاحب العمل وتواريخ بدء العمل أو انتهائه. حددوا موقع جهة العمل وما إذا كان إطار منطقة حرة معين قد ينطبق.' } },
    { title: { en: 'Keep a factual record', ar: 'احتفظوا بسجل واقعي' }, body: { en: 'Collect salary records, leave correspondence, notices, and relevant messages. Record what happened and when, without changing original documents or communications.', ar: 'اجمعوا سجلات الرواتب ومراسلات الإجازات والإشعارات والرسائل ذات الصلة. سجلوا ما حدث وتوقيته دون تعديل المستندات أو المراسلات الأصلية.' } },
    { title: { en: 'Check the appropriate next step', ar: 'تحققوا من الخطوة المناسبة' }, body: { en: 'Rights and procedures depend on the facts and the governing employment framework. Consult the relevant authority or seek individual advice before assuming a notice period, entitlement, or deadline.', ar: 'تختلف الحقوق والإجراءات بحسب الوقائع والنظام الذي يحكم علاقة العمل. راجعوا الجهة المختصة أو اطلبوا مشورة فردية قبل افتراض مدة إخطار أو استحقاق أو مهلة.' } },
  ], source: { label: 'Ministry of Human Resources & Emiratisation', url: 'https://www.mohre.gov.ae/' } },
  { slug: 'property-documents', category: 'property', title: { en: 'Documents for a property consultation', ar: 'مستندات الاستشارة العقارية' }, summary: { en: 'Prepare a clear picture of the property, the agreement, and your concern before seeking advice.', ar: 'جهزوا صورة واضحة للعقار والاتفاقية والمسألة التي تشغلكم قبل طلب المشورة.' }, sections: [
    { title: { en: 'Identify the property and parties', ar: 'حددوا العقار والأطراف' }, body: { en: 'Note the emirate, property location, your role as owner, buyer, tenant, or landlord, and the other parties involved. Procedures can vary by location and transaction type.', ar: 'حددوا الإمارة وموقع العقار وصفتكم كمالك أو مشترٍ أو مستأجر أو مؤجر والأطراف الأخرى. قد تختلف الإجراءات بحسب الموقع ونوع المعاملة.' } },
    { title: { en: 'Gather agreements and payments', ar: 'اجمعوا الاتفاقيات وإثباتات الدفع' }, body: { en: 'Keep the sale or tenancy agreement, amendments, payment receipts, handover records, and relevant notices together. Explain any missing document rather than substituting an assumption.', ar: 'اجمعوا عقد البيع أو الإيجار وتعديلاته وإيصالات الدفع ومحاضر التسليم والإشعارات ذات الصلة. وضحوا أي مستند مفقود بدلاً من الاعتماد على افتراض.' } },
    { title: { en: 'Explain the outcome you need', ar: 'وضحوا النتيجة المطلوبة' }, body: { en: 'Describe whether you need a contract review, help understanding an obligation, or advice about a dispute. Seek advice promptly if an official notice or hearing date is involved.', ar: 'وضحوا ما إذا كنتم تحتاجون إلى مراجعة عقد أو فهم التزام أو مشورة بشأن نزاع. اطلبوا المشورة سريعاً إذا كان هناك إشعار رسمي أو موعد جلسة.' } },
  ], source: { label: 'UAE Government — Housing', url: 'https://u.ae/en/information-and-services/housing' } },
  { slug: 'dispute-timeline', category: 'disputes', title: { en: 'Building a useful dispute timeline', ar: 'إعداد تسلسل زمني مفيد للنزاع' }, summary: { en: 'Separate the facts, evidence, and desired resolution before discussing a legal dispute.', ar: 'افصلوا الوقائع والأدلة والحل المطلوب قبل مناقشة النزاع القانوني.' }, sections: [
    { title: { en: 'Record key events', ar: 'سجلوا الأحداث الرئيسية' }, body: { en: 'List agreements, payments, communications, and formal notices in date order. Include any case reference or hearing information already provided by an authority.', ar: 'رتبوا الاتفاقيات والمدفوعات والمراسلات والإشعارات الرسمية حسب التاريخ. أدرجوا أي رقم قضية أو معلومات جلسة وردت من جهة مختصة.' } },
    { title: { en: 'Preserve original evidence', ar: 'حافظوا على الأدلة الأصلية' }, body: { en: 'Retain original messages and documents and make working copies. Do not publish private material or contact other parties in a way that could complicate the matter.', ar: 'احتفظوا بالرسائل والمستندات الأصلية وأعدوا نسخاً للعمل عليها. لا تنشروا مواد خاصة أو تتواصلوا مع الأطراف الأخرى بطريقة قد تعقد المسألة.' } },
    { title: { en: 'Compare options with a consultant', ar: 'ناقشوا الخيارات مع المستشار' }, body: { en: 'Discuss negotiation, settlement, or formal proceedings where appropriate. The suitable process, evidence requirements, and time limits must be assessed for your circumstances; outcomes cannot be guaranteed.', ar: 'ناقشوا التفاوض أو التسوية أو الإجراءات الرسمية بحسب الحالة. يجب تقييم المسار المناسب ومتطلبات الأدلة والمواعيد وفق ظروفكم؛ ولا يمكن ضمان النتائج.' } },
  ], source: { label: 'UAE Ministry of Justice', url: 'https://www.moj.gov.ae/' } },
  { slug: 'business-setup', category: 'business', title: { en: 'Questions to ask before setting up a business', ar: 'أسئلة قبل تأسيس الأعمال' }, summary: { en: 'Clarify your activity, location, ownership, and contractual needs before choosing a setup route.', ar: 'حددوا النشاط والموقع والملكية والاحتياجات التعاقدية قبل اختيار مسار التأسيس.' }, sections: [
    { title: { en: 'Define the activity and location', ar: 'حددوا النشاط والموقع' }, body: { en: 'Describe the intended business activity, where it will operate, and who its customers will be. Mainland and free-zone arrangements may involve different licensing requirements.', ar: 'وضحوا النشاط المقصود ومكان العمل والعملاء المستهدفين. قد تختلف متطلبات الترخيص بين البر الرئيسي والمناطق الحرة.' } },
    { title: { en: 'Discuss ownership and responsibilities', ar: 'ناقشوا الملكية والمسؤوليات' }, body: { en: 'List the proposed owners, their contributions, decision-making arrangements, and intended roles. Keep proposed partner agreements and premises documents ready for review.', ar: 'حددوا الملاك المقترحين ومساهماتهم وآلية اتخاذ القرار والأدوار المتوقعة. جهزوا اتفاقيات الشركاء المقترحة ومستندات مقر العمل للمراجعة.' } },
    { title: { en: 'Confirm requirements with the authority', ar: 'أكدوا المتطلبات مع الجهة المختصة' }, body: { en: 'Ask the relevant licensing authority about approvals, documents, and current fees. Legal consultancy can help you understand agreements and obligations; it does not itself grant a trade licence.', ar: 'اسألوا جهة الترخيص المختصة عن الموافقات والمستندات والرسوم الحالية. تساعد الاستشارة القانونية في فهم الاتفاقيات والالتزامات؛ لكنها لا تمنح رخصة تجارية بذاتها.' } },
  ], source: { label: 'UAE Government — Starting a business', url: 'https://u.ae/en/information-and-services/business/starting-a-business-in-the-uae' } },
];

export const serviceScopes: Record<string, { topics: BilingualText[]; documents: BilingualText; audience: BilingualText }> = {
  'legal-translation': { topics: [{ en: 'Clarifying the document purpose and receiving authority', ar: 'توضيح الغرض من المستند والجهة المستلمة' }, { en: 'Confirming required language versions and certification', ar: 'تأكيد اللغات المطلوبة ومتطلبات التصديق' }, { en: 'Agreeing scope, fees, and timing before proceeding', ar: 'الاتفاق على النطاق والرسوم والمدة قبل المتابعة' }], documents: { en: 'A description of the document, its original language, the required language, and the receiving authority’s requirements. Agree secure sharing before sending originals or personal records.', ar: 'وصف المستند ولغته الأصلية واللغة المطلوبة ومتطلبات الجهة المستلمة. اتفقوا على المشاركة الآمنة قبل إرسال الأصول أو السجلات الشخصية.' }, audience: { en: 'Individuals and businesses needing legal-document translation support.', ar: 'الأفراد والشركات الذين يحتاجون إلى دعم ترجمة المستندات القانونية.' } },
  litigation: { topics: [{ en: 'Reviewing the dispute timeline and available evidence', ar: 'مراجعة تسلسل النزاع والأدلة المتاحة' }, { en: 'Understanding notices, proceedings, and practical options', ar: 'فهم الإشعارات والإجراءات والخيارات العملية' }, { en: 'Considering settlement alongside formal proceedings', ar: 'بحث التسوية إلى جانب الإجراءات الرسمية' }], documents: { en: 'Agreements, correspondence, payment records, and any case notices or hearing details.', ar: 'الاتفاقيات والمراسلات وإثباتات الدفع وإشعارات القضية أو بيانات الجلسات.' }, audience: { en: 'Individuals and businesses involved in a legal dispute.', ar: 'الأفراد والشركات المعنيون بنزاع قانوني.' } },
  arbitration: { topics: [{ en: 'Reviewing arbitration clauses and dispute agreements', ar: 'مراجعة شروط التحكيم واتفاقيات النزاع' }, { en: 'Understanding the chosen forum and procedure', ar: 'فهم جهة التحكيم والإجراءات المختارة' }, { en: 'Organising supporting records and disputed obligations', ar: 'تنظيم السجلات والالتزامات محل الخلاف' }], documents: { en: 'The complete contract, arbitration clause, relevant notices, and correspondence.', ar: 'العقد كاملاً وشرط التحكيم والإشعارات والمراسلات ذات الصلة.' }, audience: { en: 'Parties to contracts that provide for arbitration or considering an agreed dispute process.', ar: 'أطراف العقود التي تتضمن التحكيم أو الراغبون في مسار متفق عليه لحل النزاع.' } },
  'real-estate': { topics: [{ en: 'Reviewing sale, purchase, and tenancy agreements', ar: 'مراجعة اتفاقيات البيع والشراء والإيجار' }, { en: 'Understanding property-related obligations', ar: 'فهم الالتزامات العقارية' }, { en: 'Considering transaction and tenancy disputes', ar: 'بحث نزاعات المعاملات والإيجارات' }], documents: { en: 'Property location, relevant agreements, payment receipts, handover records, and notices.', ar: 'موقع العقار والاتفاقيات وإيصالات الدفع ومحاضر التسليم والإشعارات.' }, audience: { en: 'Property owners, purchasers, landlords, and tenants.', ar: 'ملاك العقارات والمشترون والمؤجرون والمستأجرون.' } },
  contracts: { topics: [{ en: 'Drafting or reviewing contractual terms', ar: 'صياغة الشروط التعاقدية أو مراجعتها' }, { en: 'Clarifying payment, delivery, renewal, and termination', ar: 'توضيح الدفع والتسليم والتجديد والإنهاء' }, { en: 'Identifying risk and negotiating priorities', ar: 'تحديد المخاطر وأولويات التفاوض' }], documents: { en: 'The draft or signed agreement, schedules, amendments, and your commercial objectives.', ar: 'مسودة الاتفاقية أو نسختها الموقعة والملاحق والتعديلات والأهداف التجارية.' }, audience: { en: 'Individuals, business owners, and parties entering or reviewing an agreement.', ar: 'الأفراد وأصحاب الأعمال وأطراف الاتفاقيات الجديدة أو القائمة.' } },
  'company-formation': { topics: [{ en: 'Understanding legal setup options and obligations', ar: 'فهم خيارات التأسيس القانوني والالتزامات' }, { en: 'Reviewing ownership and partner arrangements', ar: 'مراجعة الملكية وترتيبات الشركاء' }, { en: 'Preparing questions for the licensing authority', ar: 'إعداد الأسئلة لجهة الترخيص' }], documents: { en: 'Proposed activities, ownership details, preferred location, and draft partner agreements.', ar: 'الأنشطة المقترحة وبيانات الملكية والموقع المفضل ومسودات اتفاقيات الشركاء.' }, audience: { en: 'Founders and partners planning a business in the UAE.', ar: 'المؤسسون والشركاء الذين يخططون لأعمال في الإمارات.' } },
  'family-inheritance': { topics: [{ en: 'Understanding the family or inheritance circumstances', ar: 'فهم ظروف مسائل الأسرة أو الميراث' }, { en: 'Reviewing relevant records with discretion', ar: 'مراجعة المستندات ذات الصلة بخصوصية' }, { en: 'Identifying questions about the applicable legal framework', ar: 'تحديد الأسئلة بشأن النظام القانوني الواجب التطبيق' }], documents: { en: 'A brief family timeline and a list of relevant records; agree secure sharing before providing sensitive documents.', ar: 'تسلسل عائلي موجز وقائمة بالمستندات؛ اتفقوا على المشاركة الآمنة قبل تقديم الوثائق الحساسة.' }, audience: { en: 'Individuals and families seeking private guidance on family or inheritance matters.', ar: 'الأفراد والأسر الباحثون عن مشورة خاصة في مسائل الأسرة أو الميراث.' } },
  'labour-law': { topics: [{ en: 'Reviewing employment terms and workplace obligations', ar: 'مراجعة شروط العمل والتزامات مكان العمل' }, { en: 'Understanding concerns about pay, leave, or termination', ar: 'فهم المسائل المتعلقة بالأجر أو الإجازة أو إنهاء العمل' }, { en: 'Organising records for an employment dispute', ar: 'تنظيم المستندات للنزاع العمالي' }], documents: { en: 'Employment contract, salary records, notices, and relevant workplace correspondence.', ar: 'عقد العمل وسجلات الرواتب والإشعارات والمراسلات الوظيفية.' }, audience: { en: 'Employees and employers seeking advice on an employment relationship.', ar: 'الموظفون وأصحاب العمل الباحثون عن مشورة بشأن علاقة العمل.' } },
  'criminal-cases': { topics: [{ en: 'Understanding the matter and any official notices', ar: 'فهم المسألة وأي إشعارات رسمية' }, { en: 'Reviewing relevant facts confidentially', ar: 'مراجعة الوقائع ذات الصلة بسرية' }, { en: 'Identifying appropriate professional next steps', ar: 'تحديد الخطوات المهنية المناسبة' }], documents: { en: 'A brief factual outline and details of any official reference, notice, or appointment. Avoid sending sensitive evidence through the initial form.', ar: 'وصف واقعي موجز وبيانات أي مرجع أو إشعار أو موعد رسمي. تجنبوا إرسال أدلة حساسة عبر النموذج الأولي.' }, audience: { en: 'Individuals seeking confidential consultancy about a criminal matter.', ar: 'الأفراد الباحثون عن استشارة سرية بشأن مسألة جزائية.' } },
  'dispute-resolution': { topics: [{ en: 'Clarifying the issues and desired outcome', ar: 'توضيح نقاط الخلاف والنتيجة المرجوة' }, { en: 'Considering negotiation and settlement options', ar: 'بحث خيارات التفاوض والتسوية' }, { en: 'Reviewing proposed resolution terms', ar: 'مراجعة شروط الحل المقترح' }], documents: { en: 'A dispute timeline, relevant agreements, correspondence, and any settlement proposals.', ar: 'تسلسل النزاع والاتفاقيات والمراسلات وأي مقترحات للتسوية.' }, audience: { en: 'Individuals and businesses seeking a practical way to address a disagreement.', ar: 'الأفراد والشركات الباحثون عن طريقة عملية لمعالجة الخلاف.' } },
  'personal-matters': { topics: [{ en: 'Understanding your circumstances and priorities', ar: 'فهم ظروفكم وأولوياتكم' }, { en: 'Reviewing personal agreements and obligations', ar: 'مراجعة الاتفاقيات والالتزامات الشخصية' }, { en: 'Planning appropriate next steps', ar: 'التخطيط للخطوات المناسبة' }], documents: { en: 'A short explanation of the issue, relevant dates, and a list of documents you hold.', ar: 'شرح مختصر للمسألة والتواريخ ذات الصلة وقائمة بالمستندات المتاحة.' }, audience: { en: 'Individuals seeking guidance about a personal legal concern.', ar: 'الأفراد الباحثون عن إرشاد بشأن مسألة قانونية شخصية.' } },
  'government-transactions': { topics: [{ en: 'Understanding the requirements of the relevant authority', ar: 'فهم متطلبات الجهة المختصة' }, { en: 'Reviewing supporting legal documentation', ar: 'مراجعة الوثائق القانونية الداعمة' }, { en: 'Clarifying requested corrections or additional records', ar: 'توضيح التصحيحات المطلوبة أو المستندات الإضافية' }], documents: { en: 'Authority name, transaction reference, requested documents, and any official correspondence.', ar: 'اسم الجهة ومرجع المعاملة والمستندات المطلوبة وأي مراسلات رسمية.' }, audience: { en: 'Individuals and businesses navigating government documentation requirements.', ar: 'الأفراد والشركات الذين يتعاملون مع متطلبات المستندات الحكومية.' } },
  'vehicle-transactions': { topics: [{ en: 'Reviewing vehicle sale or purchase agreements', ar: 'مراجعة اتفاقيات بيع المركبات أو شرائها' }, { en: 'Understanding documentation and payment concerns', ar: 'فهم مسائل المستندات والدفع' }, { en: 'Considering transaction-related disagreements', ar: 'بحث الخلافات المتعلقة بالمعاملة' }], documents: { en: 'Vehicle details, sale agreement, payment records, and relevant transaction correspondence.', ar: 'بيانات المركبة وعقد البيع وإثباتات الدفع والمراسلات المتعلقة بالمعاملة.' }, audience: { en: 'Vehicle buyers, sellers, and owners seeking transaction-related advice.', ar: 'مشترو المركبات وبائعوها وملاكها الباحثون عن مشورة بشأن المعاملات.' } },
  'general-consultancy': { topics: [{ en: 'Identifying the legal questions in your matter', ar: 'تحديد الأسئلة القانونية في مسألتكم' }, { en: 'Understanding available options and practical risks', ar: 'فهم الخيارات المتاحة والمخاطر العملية' }, { en: 'Agreeing a suitable scope for further advice', ar: 'الاتفاق على نطاق مناسب لمشورة إضافية' }], documents: { en: 'A brief summary, important dates, your questions, and a list of relevant records.', ar: 'ملخص موجز والتواريخ المهمة والأسئلة وقائمة بالمستندات ذات الصلة.' }, audience: { en: 'Individuals and businesses who need a clear starting point.', ar: 'الأفراد والشركات الذين يحتاجون إلى نقطة بداية واضحة.' } },
};