import type { BilingualText } from './editorial-content';

export const firmSources = {
  about: 'https://aldarlegalconsultancy.net/about-us/',
  services: 'https://aldarlegalconsultancy.net/services/',
  contact: 'https://aldarlegalconsultancy.net/contact-us/',
};

// Support areas describe published services, not unverified staff profiles.
export const teamSupport = [
  { slug: 'corporate', category: 'business', title: { en: 'Corporate & contract support', ar: 'دعم الشركات والعقود' }, summary: { en: 'Legal consultancy for business decisions, company formation, contract drafting, and employment matters.', ar: 'استشارات قانونية لقرارات الأعمال وتأسيس الشركات وصياغة العقود والمسائل العمالية.' }, service: 'contracts' },
  { slug: 'disputes', category: 'disputes', title: { en: 'Disputes & case coordination', ar: 'النزاعات وتنسيق القضايا' }, summary: { en: 'Advice on disputes and coordination with partner law firms where court representation or litigation services are required.', ar: 'مشورة بشأن النزاعات والتنسيق مع مكاتب المحاماة الشريكة عند الحاجة إلى التمثيل أمام المحاكم أو خدمات التقاضي.' }, service: 'litigation' },
  { slug: 'property', category: 'property', title: { en: 'Property & transaction support', ar: 'دعم العقارات والمعاملات' }, summary: { en: 'Guidance for property sales, purchases, agreements, and the legal questions arising from transactions.', ar: 'إرشاد لبيع العقارات وشرائها والاتفاقيات والمسائل القانونية المرتبطة بالمعاملات.' }, service: 'real-estate' },
  { slug: 'family', category: 'personal', title: { en: 'Family & personal matters', ar: 'الأسرة والمسائل الشخصية' }, summary: { en: 'Discreet consultancy for personal status, family, wills, and inheritance matters.', ar: 'استشارات تراعي الخصوصية في مسائل الأحوال الشخصية والأسرة والوصايا والميراث.' }, service: 'family-inheritance' },
  { slug: 'documents', category: 'business', title: { en: 'Translation & official documentation', ar: 'الترجمة والمستندات الرسمية' }, summary: { en: 'Support with legal translation and official transaction documentation. Confirm document and certification requirements with the office.', ar: 'دعم الترجمة القانونية ومستندات المعاملات الرسمية. أكدوا متطلبات الوثائق والتصديق مع المكتب.' }, service: 'legal-translation' },
];

export const policySections: Record<'privacy' | 'terms' | 'disclaimer', { title: BilingualText; body: BilingualText }[]> = {
  privacy: [
    { title: { en: 'Information in your inquiry', ar: 'المعلومات في استفساركم' }, body: { en: 'The inquiry form asks for your name, email, phone number, service, contact preference, and a brief description. A consultation request can also include a preferred date. Provide only what is needed to explain your question.', ar: 'يطلب النموذج الاسم والبريد الإلكتروني والهاتف والخدمة وطريقة التواصل ووصفاً موجزاً. ويمكن أن يتضمن طلب الاستشارة تاريخاً مفضلاً. قدموا فقط ما يلزم لشرح السؤال.' } },
    { title: { en: 'Email drafts and sending', ar: 'مسودات البريد والإرسال' }, body: { en: 'This website prepares an email draft in your browser; it does not save or send the inquiry through an online submission service. You decide whether to open your email application and send the message. Your email provider handles that transmission under its own terms.', ar: 'يُعد هذا الموقع مسودة بريد في المتصفح؛ ولا يحفظ الاستفسار أو يرسله عبر خدمة تقديم إلكترونية. أنتم تقررون فتح تطبيق البريد وإرسال الرسالة. يتولى مزود البريد الإرسال وفق شروطه.' } },
    { title: { en: 'Sensitive information', ar: 'المعلومات الحساسة' }, body: { en: 'Do not include identity documents, financial records, case evidence, or other highly sensitive material in the initial inquiry. Agree an appropriate document-sharing method with the office first.', ar: 'لا تدرجوا وثائق الهوية أو السجلات المالية أو أدلة القضايا أو المواد شديدة الحساسية في الاستفسار الأول. اتفقوا أولاً مع المكتب على طريقة مناسبة لمشاركة المستندات.' } },
    { title: { en: 'Appearance preference and external services', ar: 'تفضيل المظهر والخدمات الخارجية' }, body: { en: 'The light/dark preference is stored in this browser. Links to WhatsApp, maps, and official reference sites take you to external services with their own privacy practices. Web fonts and hosted images may also involve requests to their providers.', ar: 'يُحفظ تفضيل الوضع الفاتح أو الداكن في هذا المتصفح. تنقلكم روابط واتساب والخرائط والمراجع الرسمية إلى خدمات خارجية لها ممارسات خصوصية خاصة. وقد تتطلب الخطوط والصور المستضافة طلبات إلى مزوديها.' } },
    { title: { en: 'Questions about your information', ar: 'الاستفسار عن معلوماتكم' }, body: { en: 'Contact Al Dar directly about information you have sent to the office or to request correction or deletion. Retention and handling of correspondence should be confirmed directly with the office.', ar: 'تواصلوا مع الدار مباشرة بشأن المعلومات التي أرسلتموها إلى المكتب أو لطلب تصحيحها أو حذفها. أكدوا مع المكتب مباشرة كيفية التعامل مع المراسلات والاحتفاظ بها.' } },
  ],
  terms: [
    { title: { en: 'Purpose of this website', ar: 'الغرض من الموقع' }, body: { en: 'This website presents information about Al Dar Legal Consultancy and general preparation guides for legal inquiries. It is not a substitute for advice based on your documents and circumstances.', ar: 'يعرض الموقع معلومات عن الدار للاستشارات القانونية وأدلة عامة للاستعداد للاستفسار القانوني. ولا يغني عن مشورة تستند إلى مستنداتكم وظروفكم.' } },
    { title: { en: 'Requests and appointments', ar: 'الطلبات والمواعيد' }, body: { en: 'Preparing or sending an inquiry does not confirm an appointment or establish a professional engagement. The office must confirm availability, scope, any fees, and how the work will be carried out.', ar: 'إعداد الاستفسار أو إرساله لا يؤكد موعداً ولا ينشئ تكليفاً مهنياً. يجب أن يؤكد المكتب التوافر والنطاق والرسوم إن وجدت وطريقة تنفيذ العمل.' } },
    { title: { en: 'Scope and partner services', ar: 'النطاق والخدمات الشريكة' }, body: { en: 'Al Dar describes collaboration with partner law firms for court representation and litigation. Ask the office which professional or firm will handle each part of your matter and confirm the engagement terms before proceeding.', ar: 'توضح الدار تعاونها مع مكاتب محاماة شريكة للتمثيل أمام المحاكم والتقاضي. اسألوا المكتب عن المختص أو المكتب الذي سيتولى كل جزء من المسألة وأكدوا شروط التكليف قبل المتابعة.' } },
    { title: { en: 'Responsible use', ar: 'الاستخدام المسؤول' }, body: { en: 'Provide accurate information and avoid submitting confidential documents through the initial form. Do not use this website to send unlawful content or assume an urgent deadline is being monitored through an email draft.', ar: 'قدموا معلومات دقيقة وتجنبوا تقديم مستندات سرية عبر النموذج الأولي. لا تستخدموا الموقع لإرسال محتوى غير قانوني ولا تفترضوا متابعة مهلة عاجلة عبر مسودة بريد.' } },
    { title: { en: 'External references', ar: 'المراجع الخارجية' }, body: { en: 'Official links are provided as further reading. Their availability and content can change; consult the responsible authority and obtain individual advice before acting.', ar: 'تُعرض الروابط الرسمية للقراءة الإضافية. قد يتغير توافرها ومحتواها؛ راجعوا الجهة المسؤولة واحصلوا على مشورة فردية قبل اتخاذ إجراء.' } },
  ],
  disclaimer: [
    { title: { en: 'General information, not individual advice', ar: 'معلومات عامة وليست مشورة فردية' }, body: { en: 'The website and preparation guides are general information only. They do not assess your legal position, recommend a specific action, or create a consultant-client relationship.', ar: 'الموقع وأدلة الاستعداد تقدم معلومات عامة فقط. ولا تقيّم موقفكم القانوني أو توصي بإجراء محدد أو تنشئ علاقة بين المستشار والعميل.' } },
    { title: { en: 'Applicable law and deadlines', ar: 'القانون والمواعيد الواجبة' }, body: { en: 'Requirements can depend on the emirate, authority, legal framework, and facts of the matter. Laws and procedures may change. Verify current requirements and seek prompt advice about any notice or deadline.', ar: 'قد تختلف المتطلبات بحسب الإمارة والجهة والنظام القانوني ووقائع المسألة. وقد تتغير القوانين والإجراءات. تحققوا من المتطلبات الحالية واطلبوا المشورة سريعاً بشأن أي إشعار أو مهلة.' } },
    { title: { en: 'No guaranteed outcome', ar: 'لا ضمان للنتائج' }, body: { en: 'Descriptions of support areas and services do not guarantee an outcome, processing time, appointment, or fee. Confirm the scope and responsible professional directly with Al Dar.', ar: 'وصف مجالات الدعم والخدمات لا يضمن نتيجة أو مدة معالجة أو موعداً أو رسوماً. أكدوا النطاق والمختص المسؤول مباشرة مع الدار.' } },
    { title: { en: 'Editorial and business sources', ar: 'المصادر التحريرية والتجارية' }, body: { en: 'Business details are drawn from Al Dar’s public website. Preparation guides are editorial content for this website, not attributed articles by named Al Dar consultants. Official references are provided for further reading, not as endorsements.', ar: 'تستند بيانات الأعمال إلى موقع الدار العام. وأدلة الاستعداد محتوى تحريري لهذا الموقع، وليست مقالات منسوبة إلى مستشارين مسمّين في الدار. المراجع الرسمية للقراءة الإضافية وليست تأييداً للخدمات.' } },
  ],
};