import { Scale, Building2, ScrollText, Landmark, UsersRound, BriefcaseBusiness, Handshake, Gavel, HeartHandshake, Car, FileCheck2, CircleHelp } from 'lucide-react';
import type { Locale } from './i18n';
export const services = [
 {slug:'litigation',en:'Litigation',ar:'التقاضي',description:'Clear guidance through legal disputes and proceedings, focused on your objectives.',description_ar:'إرشاد واضح في النزاعات والإجراءات القانونية يركز على أهدافكم.',icon:Scale},
 {slug:'arbitration',en:'Arbitration',ar:'التحكيم',description:'Strategic advice on arbitration and alternative paths to resolving disputes.',description_ar:'مشورة استراتيجية بشأن التحكيم والطرق البديلة لحل النزاعات.',icon:Landmark},
 {slug:'real-estate',en:'Real Estate Law',ar:'القانون العقاري',description:'Practical legal guidance for property transactions, agreements, and disputes.',description_ar:'إرشاد قانوني عملي للمعاملات العقارية والاتفاقيات والنزاعات.',icon:Building2},
 {slug:'contracts',en:'Contracts & Agreements',ar:'العقود والاتفاقيات',description:'Careful drafting and review to bring clarity to your agreements and protect your interests.',description_ar:'صياغة ومراجعة دقيقة لإضفاء الوضوح على اتفاقياتكم وحماية مصالحكم.',icon:ScrollText},
 {slug:'company-formation',en:'Company Formation',ar:'تأسيس الشركات',description:'Legal consultancy to help you navigate the establishment of your business in the UAE.',description_ar:'استشارات قانونية لمساعدتكم في إجراءات تأسيس أعمالكم في الإمارات.',icon:BriefcaseBusiness},
 {slug:'family-inheritance',en:'Family & Inheritance',ar:'الأسرة والميراث',description:'Discreet advice for family and inheritance matters, with a sensitive, personal approach.',description_ar:'مشورة تراعي الخصوصية في مسائل الأسرة والميراث وبنهج إنساني.',icon:UsersRound},
 {slug:'labour-law',en:'Labour Law',ar:'قانون العمل',description:'Advice for employers and employees on workplace rights, obligations, and disputes.',description_ar:'مشورة لأصحاب العمل والموظفين حول الحقوق والالتزامات والنزاعات العمالية.',icon:Handshake},
 {slug:'criminal-cases',en:'Criminal Cases',ar:'القضايا الجزائية',description:'Confidential legal consultancy to understand your position in criminal matters.',description_ar:'استشارات قانونية سرية لفهم موقفكم في المسائل الجزائية.',icon:Gavel},
 {slug:'dispute-resolution',en:'Dispute Resolution',ar:'تسوية المنازعات',description:'Considered legal strategies for navigating disagreements and finding practical resolutions.',description_ar:'استراتيجيات قانونية مدروسة لإدارة الخلافات وإيجاد حلول عملية.',icon:HeartHandshake},
 {slug:'personal-matters',en:'Personal Legal Matters',ar:'المسائل القانونية الشخصية',description:'Individual attention and clear advice for the legal matters affecting your life.',description_ar:'اهتمام شخصي ومشورة واضحة للمسائل القانونية التي تؤثر في حياتكم.',icon:UsersRound},
 {slug:'government-transactions',en:'Government Transactions',ar:'المعاملات الحكومية',description:'Guidance on documentation and transaction clearance, including Tasheel-related services. Confirm current availability with the office.',description_ar:'إرشاد للمستندات وتخليص المعاملات، بما فيها الخدمات المتعلقة بتسهيل. أكدوا التوافر الحالي مع المكتب.',icon:FileCheck2},
 {slug:'vehicle-transactions',en:'Vehicle Transactions',ar:'معاملات المركبات',description:'Legal assistance with vehicle-related transactions and their documentation.',description_ar:'مساعدة قانونية في معاملات المركبات والمستندات ذات الصلة.',icon:Car},
 {slug:'general-consultancy',en:'General Legal Consultancy',ar:'الاستشارات القانونية العامة',description:'A clear starting point for understanding your rights, options, and next steps.',description_ar:'نقطة بداية واضحة لفهم حقوقكم وخياراتكم وخطواتكم المقبلة.',icon:CircleHelp},
 {slug:'legal-translation',en:'Legal Translation',ar:'الترجمة القانونية',description:'Support with translation of legal documents. Confirm languages, certification requirements, fees, and timing directly with the office.',description_ar:'دعم ترجمة المستندات القانونية. أكدوا اللغات ومتطلبات التصديق والرسوم والمدة مباشرة مع المكتب.',icon:ScrollText},
];
export function local(locale:Locale,en:string,ar:string) { return locale==='ar'?ar:en; }
export const faqs = [
 {en:'How do I request a legal consultation?',ar:'كيف يمكنني طلب استشارة قانونية؟',answer:'Complete our consultation request form or contact us by phone, email, or WhatsApp. Our team will review your matter and contact you to discuss the next steps.',answer_ar:'أكملوا نموذج طلب الاستشارة أو تواصلوا معنا عبر الهاتف أو البريد الإلكتروني أو واتساب. سيراجع فريقنا طلبكم ويتواصل معكم لمناقشة الخطوات التالية.'},
 {en:'Can I request advice in Arabic or English?',ar:'هل يمكنني طلب المشورة بالعربية أو الإنجليزية؟',answer:'You can select Arabic or English as your preferred language when submitting an inquiry.',answer_ar:'يمكنكم اختيار العربية أو الإنجليزية كلغة مفضلة عند إرسال استفساركم.'},
 {en:'Is my inquiry confidential?',ar:'هل استفساري سري؟',answer:'We handle inquiries with discretion. Please share only a brief description initially and avoid sending highly sensitive documents until our team requests them.',answer_ar:'نتعامل مع الاستفسارات بخصوصية. يرجى مشاركة وصف موجز أولاً وتجنب إرسال المستندات شديدة الحساسية حتى يطلبها فريقنا.'},
 {en:'Does a request confirm an appointment?',ar:'هل الطلب يؤكد موعد الاستشارة؟',answer:'No. Your preferred date is a request only. Our team will contact you to confirm availability, the consultation scope, and any applicable fees.',answer_ar:'لا، التاريخ المفضل هو طلب فقط. سيتواصل معكم فريقنا لتأكيد التوافر ونطاق الاستشارة وأي رسوم تنطبق.'},
 {en:'Where is Al Dar Legal Consultancy located?',ar:'أين تقع الدار للاستشارات القانونية؟',answer:'Office 308, 3rd Floor, Fujairah Trade Centre, 88 Sheikh Hamad Bin Abdullah Al Sharqi Road, Fujairah, United Arab Emirates.',answer_ar:'مكتب 308، الطابق الثالث، مركز الفجيرة التجاري، 88 شارع الشيخ حمد بن عبدالله الشرقي، الفجيرة، الإمارات العربية المتحدة.'},
 {en:'What are the office opening hours?',ar:'ما أوقات عمل المكتب؟',answer:'The official website lists Monday–Friday, 08:00–17:00, and Saturday–Sunday, 08:00–14:00 (UAE time). Call ahead to confirm availability and public-holiday hours.',answer_ar:'يعرض الموقع الرسمي الدوام من الاثنين إلى الجمعة، 08:00–17:00، والسبت والأحد، 08:00–14:00 بتوقيت الإمارات. اتصلوا مسبقاً لتأكيد التوافر وأوقات العطلات الرسمية.'},
 {en:'Who handles court representation?',ar:'من يتولى التمثيل أمام المحاكم؟',answer:'Al Dar’s official website describes strategic partnerships with law firms for court representation and litigation. Confirm the responsible firm, professional, and engagement terms directly with the office.',answer_ar:'يوضح موقع الدار الرسمي وجود شراكات استراتيجية مع مكاتب محاماة للتمثيل أمام المحاكم والتقاضي. أكدوا المكتب والمختص المسؤول وشروط التكليف مباشرة مع المكتب.'},
 {en:'Can you help with legal translation and Tasheel transactions?',ar:'هل تتوفر مساعدة في الترجمة القانونية ومعاملات تسهيل؟',answer:'The firm publicly lists legal translation and government transaction clearance, including Tasheel-related support. Contact the office to confirm the documents, languages, authority requirements, and current availability.',answer_ar:'يعلن المكتب عن الترجمة القانونية وتخليص المعاملات الحكومية، بما فيها الدعم المتعلق بتسهيل. تواصلوا معه لتأكيد المستندات واللغات ومتطلبات الجهة والتوافر الحالي.'},
 {en:'Does the website send my inquiry automatically?',ar:'هل يرسل الموقع استفساري تلقائياً؟',answer:'No. The form prepares a validated email draft. Open your email application and send it yourself, or contact the office by phone or WhatsApp. Preparing a draft does not deliver a message.',answer_ar:'لا. يُعد النموذج مسودة بريد بعد التحقق من البيانات. افتحوا تطبيق البريد وأرسلوها بأنفسكم أو تواصلوا بالهاتف أو واتساب. إعداد المسودة لا يرسل الرسالة.'},
 {en:'What should I prepare for a consultation?',ar:'ماذا أجهز للاستشارة؟',answer:'Prepare a short timeline, your main questions, and a list of relevant agreements, correspondence, and notices. Agree a suitable document-sharing method with the office before sending sensitive records.',answer_ar:'جهزوا تسلسلاً زمنياً مختصراً وأسئلتكم الرئيسية وقائمة بالاتفاقيات والمراسلات والإشعارات ذات الصلة. اتفقوا مع المكتب على طريقة مناسبة لمشاركة المستندات قبل إرسال سجلات حساسة.'},
];
