import { Link } from '@tanstack/react-router';
import { BookOpen, UsersRound } from 'lucide-react';
import { CollectionView } from './collection-view';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './ui/accordion';
import { ConsultationLink, ContactPanel, PageIntro } from './legal-site';
import { serviceCategories } from '@/lib/collection-categories';
import { guides, guidanceCategories } from '@/lib/editorial-content';
import { firmSources, policySections, teamSupport } from '@/lib/firm-content';
import { t, type Locale } from '@/lib/i18n';

export function FirmSource({ locale, kind = 'about' }: { locale: Locale; kind?: keyof typeof firmSources }) {
  return <p className="content-source"><a href={firmSources[kind]} target="_blank" rel="noopener noreferrer">{locale === 'en' ? 'Business information source: Al Dar’s official website' : 'مصدر معلومات المكتب: موقع الدار الرسمي'} ↗</a></p>;
}

export function TeamPage({ locale }: { locale: Locale }) {
  return <><PageIntro locale={locale} title={t(locale, 'team.title')} description={t(locale, 'team.sub')} />
    <section className="section"><div className="site-container form-layout"><div><div className="eyebrow">{locale === 'en' ? 'People & partnerships' : 'الفريق والشراكات'}</div><h2>{locale === 'en' ? 'The right support for your matter.' : 'الدعم المناسب لمسألتكم.'}</h2><p className="section-copy mt-6">{locale === 'en' ? 'Established in Fujairah in 2019, Al Dar provides consultancy for individuals and businesses across corporate, property, family, and dispute matters. The office coordinates with partner law firms for court representation and litigation services.' : 'تأسست الدار في الفجيرة عام 2019، وتقدم الاستشارات للأفراد والشركات في مسائل الشركات والعقارات والأسرة والنزاعات. ينسق المكتب مع مكاتب المحاماة الشريكة للتمثيل أمام المحاكم وخدمات التقاضي.'}</p><p className="section-copy">{locale === 'en' ? 'Current named consultant profiles are not publicly verified. Contact the office to confirm who will handle your matter, their role, the scope of work, and any partner-firm involvement before engagement.' : 'لم تتوفر ملفات عامة موثقة بأسماء المستشارين الحاليين. تواصلوا مع المكتب لتأكيد من سيتولى مسألتكم ودوره ونطاق العمل وأي مشاركة لمكتب شريك قبل التكليف.'}</p><FirmSource locale={locale} /><ConsultationLink locale={locale} /></div><ContactPanel locale={locale} /></div></section>
    <section className="section bg-secondary"><div className="site-container"><div className="eyebrow">{locale === 'en' ? 'Support areas, not individual staff profiles' : 'مجالات الدعم وليست ملفات موظفين'}</div><h2 className="mb-8">{locale === 'en' ? 'Expertise organised around your needs.' : 'خبرة منظمة حول احتياجاتكم.'}</h2><CollectionView key={locale} locale={locale} items={teamSupport} searchText={item => `${item.title.en} ${item.title.ar} ${item.summary.en} ${item.summary.ar}`} title={item => item.title[locale]} category={item => item.category} categories={serviceCategories(locale)} searchPlaceholder={locale === 'en' ? 'Search support areas…' : 'ابحثوا في مجالات الدعم…'} defaultPageSize={3}>{items => <div className="service-grid">{items.map(item => <Link key={item.slug} to="/$locale/services/$slug" params={{ locale, slug: item.service }} className="service-card"><UsersRound className="service-icon" /><h3>{item.title[locale]}</h3><p>{item.summary[locale]}</p><span className="service-link">{t(locale, 'cta.learnMore')} ↗</span></Link>)}</div>}</CollectionView></div></section></>;
}

export function InsightsPage({ locale }: { locale: Locale }) {
  return <><PageIntro locale={locale} title={t(locale, 'insights.title')} description={t(locale, 'insights.sub')} /><section className="section"><div className="site-container"><p className="editorial-notice">{locale === 'en' ? 'General preparation guides for UAE legal inquiries — editorial information, not individual legal advice or publications attributed to named Al Dar consultants.' : 'أدلة عامة للاستعداد للاستفسارات القانونية في الإمارات — معلومات تحريرية وليست مشورة فردية أو منشورات منسوبة إلى مستشارين مسمّين في الدار.'}</p><CollectionView key={locale} locale={locale} items={guides} searchText={guide => `${guide.title.en} ${guide.title.ar} ${guide.summary.en} ${guide.summary.ar}`} title={guide => guide.title[locale]} category={guide => guide.category} categories={guidanceCategories(locale)} searchPlaceholder={locale === 'en' ? 'Search guides…' : 'ابحثوا في الأدلة…'} defaultPageSize={3}>{items => <div className="service-grid">{items.map(guide => <article className="service-card guide-card" key={guide.slug}><BookOpen className="service-icon" /><div className="eyebrow">{guidanceCategories(locale).find(category => category.value === guide.category)?.label}</div><h3>{guide.title[locale]}</h3><p>{guide.summary[locale]}</p><Accordion type="single" collapsible><AccordionItem value={guide.slug}><AccordionTrigger>{locale === 'en' ? 'Read preparation guide' : 'قراءة دليل الاستعداد'}</AccordionTrigger><AccordionContent>{guide.sections.map(section => <div className="guide-section" key={section.title.en}><h4>{section.title[locale]}</h4><p>{section.body[locale]}</p></div>)}<a className="content-source" href={guide.source.url} target="_blank" rel="noopener noreferrer">{locale === 'en' ? 'Official reference — further reading' : 'مرجع رسمي — قراءة إضافية'} ↗</a></AccordionContent></AccordionItem></Accordion></article>)}</div>}</CollectionView><p className="content-source mt-8">{t(locale, 'insights.disclaimer')}</p><ConsultationLink locale={locale} /></div></section></>;
}

export function FullPolicyPage({ locale, kind }: { locale: Locale; kind: 'privacy' | 'terms' | 'disclaimer' }) {
  return <><PageIntro locale={locale} title={t(locale, `footer.${kind}`)} /><section className="section"><div className="site-container form-layout"><div>{policySections[kind].map(section => <section className="policy-section" key={section.title.en}><h2>{section.title[locale]}</h2><p className="section-copy mt-4">{section.body[locale]}</p></section>)}{kind === 'disclaimer' && <FirmSource locale={locale} kind="services" />}</div><ContactPanel locale={locale} /></div></section></>;
}