/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleConsultationRouteImport } from './routes/$locale.consultation'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocaleDisclaimerRouteImport } from './routes/$locale.disclaimer'
import { Route as LocaleFaqRouteImport } from './routes/$locale.faq'
import { Route as LocaleInsightsRouteImport } from './routes/$locale.insights'
import { Route as LocalePracticeAreasRouteImport } from './routes/$locale.practice-areas'
import { Route as LocalePrivacyRouteImport } from './routes/$locale.privacy'
import { Route as LocaleServicesRouteImport } from './routes/$locale.services'
import { Route as LocaleTeamRouteImport } from './routes/$locale.team'
import { Route as LocaleTermsRouteImport } from './routes/$locale.terms'
import { Route as LocaleServicesIndexRouteImport } from './routes/$locale.services.index'
import { Route as LocaleServicesSlugRouteImport } from './routes/$locale.services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleConsultationRoute = LocaleConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDisclaimerRoute = LocaleDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleInsightsRoute = LocaleInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePracticeAreasRoute = LocalePracticeAreasRouteImport.update({
  id: '/practice-areas',
  path: '/practice-areas',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesRoute = LocaleServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTeamRoute = LocaleTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesIndexRoute = LocaleServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleServicesRoute,
} as any)
const LocaleServicesSlugRoute = LocaleServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/consultation': typeof LocaleConsultationRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/disclaimer': typeof LocaleDisclaimerRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/insights': typeof LocaleInsightsRoute
  '/$locale/practice-areas': typeof LocalePracticeAreasRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/services': typeof LocaleServicesRouteWithChildren
  '/$locale/team': typeof LocaleTeamRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/services/$slug': typeof LocaleServicesSlugRoute
  '/$locale/services/': typeof LocaleServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/consultation': typeof LocaleConsultationRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/disclaimer': typeof LocaleDisclaimerRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/insights': typeof LocaleInsightsRoute
  '/$locale/practice-areas': typeof LocalePracticeAreasRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/team': typeof LocaleTeamRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/services/$slug': typeof LocaleServicesSlugRoute
  '/$locale/services': typeof LocaleServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/consultation': typeof LocaleConsultationRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/disclaimer': typeof LocaleDisclaimerRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/insights': typeof LocaleInsightsRoute
  '/$locale/practice-areas': typeof LocalePracticeAreasRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/services': typeof LocaleServicesRouteWithChildren
  '/$locale/team': typeof LocaleTeamRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/services/$slug': typeof LocaleServicesSlugRoute
  '/$locale/services/': typeof LocaleServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/consultation'
    | '/$locale/contact'
    | '/$locale/disclaimer'
    | '/$locale/faq'
    | '/$locale/insights'
    | '/$locale/practice-areas'
    | '/$locale/privacy'
    | '/$locale/services'
    | '/$locale/team'
    | '/$locale/terms'
    | '/$locale/'
    | '/$locale/services/$slug'
    | '/$locale/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/about'
    | '/$locale/consultation'
    | '/$locale/contact'
    | '/$locale/disclaimer'
    | '/$locale/faq'
    | '/$locale/insights'
    | '/$locale/practice-areas'
    | '/$locale/privacy'
    | '/$locale/team'
    | '/$locale/terms'
    | '/$locale'
    | '/$locale/services/$slug'
    | '/$locale/services'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/consultation'
    | '/$locale/contact'
    | '/$locale/disclaimer'
    | '/$locale/faq'
    | '/$locale/insights'
    | '/$locale/practice-areas'
    | '/$locale/privacy'
    | '/$locale/services'
    | '/$locale/team'
    | '/$locale/terms'
    | '/$locale/'
    | '/$locale/services/$slug'
    | '/$locale/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/consultation': {
      id: '/$locale/consultation'
      path: '/consultation'
      fullPath: '/$locale/consultation'
      preLoaderRoute: typeof LocaleConsultationRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/disclaimer': {
      id: '/$locale/disclaimer'
      path: '/disclaimer'
      fullPath: '/$locale/disclaimer'
      preLoaderRoute: typeof LocaleDisclaimerRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/insights': {
      id: '/$locale/insights'
      path: '/insights'
      fullPath: '/$locale/insights'
      preLoaderRoute: typeof LocaleInsightsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/practice-areas': {
      id: '/$locale/practice-areas'
      path: '/practice-areas'
      fullPath: '/$locale/practice-areas'
      preLoaderRoute: typeof LocalePracticeAreasRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services': {
      id: '/$locale/services'
      path: '/services'
      fullPath: '/$locale/services'
      preLoaderRoute: typeof LocaleServicesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/team': {
      id: '/$locale/team'
      path: '/team'
      fullPath: '/$locale/team'
      preLoaderRoute: typeof LocaleTeamRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services/': {
      id: '/$locale/services/'
      path: '/'
      fullPath: '/$locale/services/'
      preLoaderRoute: typeof LocaleServicesIndexRouteImport
      parentRoute: typeof LocaleServicesRoute
    }
    '/$locale/services/$slug': {
      id: '/$locale/services/$slug'
      path: '/$slug'
      fullPath: '/$locale/services/$slug'
      preLoaderRoute: typeof LocaleServicesSlugRouteImport
      parentRoute: typeof LocaleServicesRoute
    }
  }
}

interface LocaleServicesRouteChildren {
  LocaleServicesSlugRoute: typeof LocaleServicesSlugRoute
  LocaleServicesIndexRoute: typeof LocaleServicesIndexRoute
}

const LocaleServicesRouteChildren: LocaleServicesRouteChildren = {
  LocaleServicesSlugRoute: LocaleServicesSlugRoute,
  LocaleServicesIndexRoute: LocaleServicesIndexRoute,
}

const LocaleServicesRouteWithChildren = LocaleServicesRoute._addFileChildren(
  LocaleServicesRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleConsultationRoute: typeof LocaleConsultationRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleDisclaimerRoute: typeof LocaleDisclaimerRoute
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocaleInsightsRoute: typeof LocaleInsightsRoute
  LocalePracticeAreasRoute: typeof LocalePracticeAreasRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleServicesRoute: typeof LocaleServicesRouteWithChildren
  LocaleTeamRoute: typeof LocaleTeamRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleConsultationRoute: LocaleConsultationRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleDisclaimerRoute: LocaleDisclaimerRoute,
  LocaleFaqRoute: LocaleFaqRoute,
  LocaleInsightsRoute: LocaleInsightsRoute,
  LocalePracticeAreasRoute: LocalePracticeAreasRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleServicesRoute: LocaleServicesRouteWithChildren,
  LocaleTeamRoute: LocaleTeamRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
